export const TAB_NAVIGATOR = "TAB_NAVIGATOR"

// Unlogged Screens
export const WELCOME_SCREEN = 'WELCOME_SCREEN'
export const AUTHENTICATION_SCREEN = 'AUTHENTICATION_SCREEN'
export const TERMS_SCREEN = "TERMS_SCREEN"
export const SIGN_UP_SCREEN = "SIGN_UP_SCREEN"

// Logged Screens
export const NOTIFICATIONS_SCREEN = "NOTIFICATIONS_SCREEN"
export const HOME_SCREEN = "HOME_SCREEN"
export const HELP_SCREEN = "HELP_SCREEN"
