export const REQUEST_LOGIN = '/login/request/'
export const LOGIN = '/login'
export const SIGN_UP = '/signup'
export const UPDATE = '/user/'
export const USERS_LIST = '/user/list'
export const SCHEDULES = '/schedule/'
