export const REQUEST_LOGIN = '/login/request/'
export const LOGIN = '/login'
export const SOCIAL_LOGIN = '/login/social'
export const SIGN_UP = '/signup'
export const UPDATE = '/user/'
export const USERS = '/user/list'
export const SCHEDULES = '/schedule/'
export const VERIFY_TOKEN = '/user/verify-token'
